
;░█▄█░█▀█░█▀▀░█░█░▀█▀░█▀█░█▀▀░░░█▀▀░█▀▀░▀█▀░▀█▀░▀█▀░█▀█░█▀▀░█▀▀
;░█░█░█▀█░█░░░█▀█░░█░░█░█░█▀▀░░░▀▀█░█▀▀░░█░░░█░░░█░░█░█░█░█░▀▀█
;░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░▀░▀▀▀░░░▀▀▀░▀▀▀░░▀░░░▀░░▀▀▀░▀░▀░▀▀▀░▀▀▀

;░█▀▄░█▀█░░░█▀█░█▀█░▀█▀░░░█▀▀░█▀▄░▀█▀░▀█▀░░░█▀█░█▀█░█▀▀░▀█▀░░░█░█░█▀▀░█▀▄░█▀▀░█░█░█
;░█░█░█░█░░░█░█░█░█░░█░░░░█▀▀░█░█░░█░░░█░░░░█▀▀░█▀█░▀▀█░░█░░░░█▀█░█▀▀░█▀▄░█▀▀░▀░▀░▀
;░▀▀░░▀▀▀░░░▀░▀░▀▀▀░░▀░░░░▀▀▀░▀▀░░▀▀▀░░▀░░░░▀░░░▀░▀░▀▀▀░░▀░░░░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░▀░▀

; Please use Machine_user_vars.g instead to override any of these settings 
; as this file is included as part of each release and your settings will be overridden!!!!

; This sets the general machine travel speeds for things like parking etc
; X and Y are the first value, Z is the second value.
; Both values are in mm/s
global Machine_travel_speed = {150, 5} ; was AFC_travel_speed

; This sets whether there are any debug messages or not
; The default is false
global Machine_debug = false ; was AFC_debug

; This sets which features of the load/unload process you want to enable
; They are in the order of
; brush
var brush = false
; cut
var cut = false
; kick
var kick = false
; park
var park = false
; poop
var poop = false
; purge
var purge = false
; carry out a startup check
var start = false
; spoolman support
; this sets whether spoolman filament tracking support is to be enabled
; 0 = disabled
; 1 = enabled
var spoolman = 0
; initial unload
; 0 = use measurements
; 1 = use the global_machine_extruder_switches[0] which in the input switch. This must be condifured
var initial_unload = 0

; This is the Object Model Number of the axis we use for loading the filament. 
; If you just have X, Y and Z then this should be set to 3. Each additional axis you've added will increment this number
global Machine_om_axis_number = 3 ; was om_axis_number

; These are the measurements of your extruder setup. 
; Overall length from input to nozzle, input to cutter, cutter to nozzle. All values are in mm
global Machine_extruder_measurements = {125,40,80} ; These are the measurements of your extruder setup. Overall length from input to nozzle, input to cutter, cutter to nozzle
; was main_extruder_measurements

; These are the switches either side of the extruder if installed.
; First is the switch above the extruder
; Second is the switch below the extruder
; These are absolute input addresses because they are expected to not be on an expansion board
; Assumed not used, so nil,nil by default
global Machine_extruder_switches = { "nil", "nil" } ; was extruder_switches

; These are used as part of the start_print.g
; This is how long to soak the printer with the bed on when printing ABS or ASA. Value is in minutes
global Machine_soak_time = 15 ; was soakTime 
; Used to check whether the gcode sliced is for the nozzle size installed in this printer  
global Machine_nozzle_diameter = 0.4 ; was nozzleDiameterInstalled  
; This is a list of the filaments to soak for. The filament name must match the name generated by the slicer gcode
global Machine_filament_soak = {"ABS","ASA"} ; was filamentSoak

;░█▀▀░█░█░▀█▀░░░█▀▀░█▀▀░▀█▀░▀█▀░▀█▀░█▀█░█▀▀░█▀▀
;░█░░░█░█░░█░░░░▀▀█░█▀▀░░█░░░█░░░█░░█░█░█░█░▀▀█
;░▀▀▀░▀▀▀░░▀░░░░▀▀▀░▀▀▀░░▀░░░▀░░▀▀▀░▀░▀░▀▀▀░▀▀▀

; This should be the position of the toolhead where the cutter arm just
; lightly touches the depressor pin
; The first value is the x coordinate and the second value is the y coordinate
; AFC_Marco_Vars.cfg line 32
global Machine_cut_location = {-1,-1} ; was AFC_cut_location

; Direction to make the cut move (left, right, front, back).
; Make sure the word you change to is all lowercase
; AFC_Marco_Vars.cfg line 38
global Machine_cut_direction = "left" ; was AFC_cut_direction

; Park
; This distance is used to move toolhead to cut filament
; and to create a small saftely distance that aids in generating momentum
; Position of the toolhead when the cutter is fully compressed.
; Move
; Distance the toolhead needs to travel to compress the cutter arm.
; To calculate this distance start at the pin_loc_xy position and move
; your toolhead till the cutter arm is completely compressed. Take 0.5mm off this distance
; as a buffer. 
; Ex pin_loc_x : 9, 310  fully compressed at 0, 310 set cut_move_dist to 8.5
; AFC_Marco_Vars.cfg line 42 for the first value and line 50 for the second
global Machine_cut_dist = {6.0,8.5} ; park (mm) and move (mm)
; was AFC_cut_dist

; Speed related settings for tip cutting
; Note that if the cut speed is too fast, the steppers can lose steps.
; Therefore, for a cut:
; - We first make a fast move to accumulate some momentum and get the cut
;   blade to the initial contact with the filament
; - We then make a slow move for the actual cut to happen 
; AFC_Marco_Vars.cfg lines 58 to 63 and line 77
global Machine_cut_move = {32,10,150,50,0.85,25,2} ; Fast speed (mm/s), slow speed (mm/s), evacuate speed (mm/s), dwell time (ms), fast move fraction, extruder move speed (ms) and cut count
; was AFC_cut_move

; If the toolhead returns to initial position after the cut is complete.
; AFC_Marco_Vars.cfg line 66
global Machine_cut_restore_pos = false ; True = return to initial position, False = don't return
; was AFC_cut_restore_pos

; Distance to retract prior to making the cut, this reduces wasted filament but might cause clog 
; if set too large and/or if there are gaps in the hotend assembly 
; *This must be less than the distance from the nozzle to the cutter
; AFC_Marco_Vars.cfg line 71
global Machine_cut_retract_length = 20 ; Distance (mm)
; was AFC_cut_retract_length

; This can help prevent clogging of some toolheads by doing a quick tip from to reduce stringing
; AFC_Marco_Vars.cfg line 74
global Machine_cut_quick_tip_forming = false ; true or false
; was AFC_cut_quick_tip_forming

; Retract length and speed after the cut so that the cutter can go back 
; into its origin position
; AFC_Marco_Vars.cfg line 81 and 82
global Machine_cut_rip = {1.0,3} ; Distance (mm), speed (mm/s)
; was AFC_cut_rip

; Pushback of the remaining tip from the cold end into the hotend
; *Must be less then retract_length
; AFC_Marco_Vars.cfg line 86 and 87
global Machine_cut_pushback = {15,20} ; Distance (mm) and time to dwell between the pushback
; was AFC_cut_pushback

; Safety margin for fast vs slow travel. When traveling to the pin location
; we make a safer but longer move if we are closer to the pin than this
; specified margin. Usually setting these to the size of the toolhead
; (plus a small margin) should be good enough 
; AFC_Marco_Vars.cfg line 93
global Machine_cut_safe_margin = {30,30} ; X and Y, approx toolhead width +5mm, height +5mm
; was AFC_cut_safe_margin

; Some printers may need a boost of power to complete the cut without skipping steps.
; One option is to increase the current for thost steppers in config.g. Another
; option is to use these variables to set a current that is only used during the
; cut motion. Different combinations of kinematics and cutter configurations engage
; different combinations of steppers for that motion.  Set the needed variables.
; The override is skipped if the current is 0.
; Enable if layer shifts occur when cutting
; AFC_Marco_Vars.cfg lines 103 and 105
global Machine_cut_current_stepper = {0,0,0} ; X, Y and Z in mA
; was AFC_cut_current_stepper

;░█▀█░█▀█░█▀█░█▀█░░░█▀▀░█▀▀░▀█▀░▀█▀░▀█▀░█▀█░█▀▀░█▀▀
;░█▀▀░█░█░█░█░█▀▀░░░▀▀█░█▀▀░░█░░░█░░░█░░█░█░█░█░▀▀█
;░▀░░░▀▀▀░▀▀▀░▀░░░░░▀▀▀░▀▀▀░░▀░░░▀░░▀▀▀░▀░▀░▀▀▀░▀▀▀

; Sets the poop location in X and Y
; AFC_Marco_Vars.cfg line 129
global Machine_purge_location = {-1,-1} ; X, Y location of where to purge
; was AFC_purge_location

; Sets the extrusion speed for the purge
; AFC_Marco_Vars.cfg line 130
global Machine_purge_speed = 6.5 ; speed (mm/s) of the purge
; was AFC_purge_speed

; Set to False to not move in Z during poop
; AFC_Marco_Vars.cfg line 131
global Machine_z_purge_move = true 
; was AFC_z_purge_move

; Speed, in mm/s to lift z after the purge is completed. Its a faster lift to keep it from 
; sticking to the toolhead
; height to raise above the final purge position after the purge is completed as part of the fast z move
; example: If final poop height ends at 20mm this variable will raise Z to 30mm
; AFC_Marco_Vars.cfg line 135 and 136
global Machine_purge_fast_z = {200,20} ; speed (mm/s), height (mm)
; was AFC_purge_fast_z

; If the toolhead returns to initial position after the poop is complete.
; AFC_Marco_Vars.cfg line 140
global Machine_purge_restore = false ; True = return to initial position, False = don't return
; was AFC_purge_restore

; The height to raise the nozzle above the tray before purging. This allows any built up 
; pressure to escape before the purge.
; AFC_Marco_Vars.cfg line 145
global Machine_purge_start = 0.6
; was AFC_purge_start

; Set the part cooling fan speed. Disabling can help prevent the nozzle from cooling down 
; and stimulate flow, Enabling it can prevent blobs from sticking together.
; AFC_Marco_Vars.cfg line 149 to 151
global Machine_part_cooling_fan = {true,1.0,2} ; Run at full speed, speed to run fan when enabled (0 to 1.0), time to pause after purge to allow fan to cool the poop (s)
; was AFC_part_cooling_fan

; ==================== PURGE LENGTH TUNING
; Default purge length to fall back on when neither the tool map purge_volumes or 
; parameter PURGE_LENGTH is set.
; AFC_Marco_Vars.cfg line 156 and line 160
global Machine_purge_length = {72.111,60.999} ; Default purge length (mm), absolute minimum purge length (mm)
; was AFC_purge_length

; The slicer values often are a bit too wasteful. Tune it here to get optimal values. 0.6
; is a good starting point.
; AFC_Marco_Vars.cfg line 164
global Machine_purge_length_modifier = 1
; was AFC_purge_length_modifier

; Length of filament to add after the purge volume. Purge volumes don't always take 
; cutters into account and therefor a swap from red to white might be long enough, but 
; from white to red can be far too short. When should you alter this value:
;   INCREASE: When the dark to light swaps are good, but light to dark aren't.
;   DECREASE: When the light to dark swaps are good, but dark to light aren't. Don't 
;     forget to increase the purge_length_modifier
; AFC_Marco_Vars.cfg line 172
global Machine_purge_length_addition = 0
; was AFC_purge_length_addition

;░█░█░▀█▀░█▀▀░█░█░░░█▀▀░█▀▀░▀█▀░▀█▀░▀█▀░█▀█░█▀▀░█▀▀
;░█▀▄░░█░░█░░░█▀▄░░░▀▀█░█▀▀░░█░░░█░░░█░░█░█░█░█░▀▀█
;░▀░▀░▀▀▀░▀▀▀░▀░▀░░░▀▀▀░▀▀▀░░▀░░░▀░░▀▀▀░▀░▀░▀▀▀░▀▀▀

; Location to move before kick - X, Y and Z
; Height to drop to for kick move
; Speed of kick movement
; Accel of kick moves. This will overwrite the global accel for this macro. Set to 0 to use global accel
; Direction to make the kick move (left, right, front, back)
; How far to move to kick poop off
; Height of z after kick move
; AFC_Marco_Vars.cfg line 182 to 188
global Machine_kick = {-1,-1,5,1.5,150,0,"right",45,10} ; was AFC_kick

;░█▀▄░█▀▄░█░█░█▀▀░█░█░░░█▀▀░█▀▀░▀█▀░▀█▀░▀█▀░█▀█░█▀▀░█▀▀
;░█▀▄░█▀▄░█░█░▀▀█░█▀█░░░▀▀█░█▀▀░░█░░░█░░░█░░█░█░█░█░▀▀█
;░▀▀░░▀░▀░▀▀▀░▀▀▀░▀░▀░░░▀▀▀░▀▀▀░░▀░░░▀░░▀▀▀░▀░▀░▀▀▀░▀▀▀

; Position of the center of the brush (Set z to -1 if you dont want a z move) - X(0), Y(1) and Z(2)
; 3 - Speed of cleaning moves when brushing
; 4 - Total width in mm of the brush in the X direction
; 5 - Total depth in mm of the brush in the Y direction
; 6 - True - Brush along Y axis first then X. False - Only brush along x
; 7 - Number of passes to make on the brush.
; AFC_Marco_Vars.cfg line 199 to 206
; 8 - Whether the brush is on a servo or on a motor for deployment
; 9 - Servo pin number
; 10 - Deployed angle
; 11 - Retracted angle
; 12 - Servo number (for M950)
; 13 - brush clean acceleration
; 14 - True - Z needs to be above a certain height for brush deployment. False - No minimum z height required
; 15 - Safe brush - True or false - The head needs to be away from a certain position to allow the brush to be deployed
; Position that the head needs to be in to allow the brush to deploy - X(16), Y(17), Z(18)
global Machine_brush = {-1,-1,-1,150,30,10,true,4,false,"0.PE6",110,20,10,0,false,false,-1,-1,-1} ; was AFC_brush

;░█▀█░█▀█░█▀▄░█░█░░░█▀▀░█▀▀░▀█▀░▀█▀░▀█▀░█▀█░█▀▀░█▀▀
;░█▀▀░█▀█░█▀▄░█▀▄░░░▀▀█░█▀▀░░█░░░█░░░█░░█░█░█░█░▀▀█
;░▀░░░▀░▀░▀░▀░▀░▀░░░▀▀▀░▀▀▀░░▀░░░▀░░▀▀▀░▀░▀░▀▀▀░▀▀▀

; AFC_Marco_Vars.cfg line 225 to 228
global Machine_park = {-1,-1,0} ; Park location in X, Y and Z
; was AFC_park

;░▀█▀░▀█▀░█▀█░░░█▀▀░█▀█░█▀▄░█▄█░▀█▀░█▀█░█▀▀░░░█▀▀░█▀▀░▀█▀░▀█▀░▀█▀░█▀█░█▀▀░█▀▀
;░░█░░░█░░█▀▀░░░█▀▀░█░█░█▀▄░█░█░░█░░█░█░█░█░░░▀▀█░█▀▀░░█░░░█░░░█░░█░█░█░█░▀▀█
;░░▀░░▀▀▀░▀░░░░░▀░░░▀▀▀░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░░░▀▀▀░▀▀▀░░▀░░░▀░░▀▀▀░▀░▀░▀▀▀░▀▀▀

; This is the initial press of the filament into the tip before any cooling moves.
; AFC.cfg line 117
global Machine_tip_ramming_volume = 0 ; was AFC_tip_ramming_volume

; Set this if you would like a temperature reduction during the tip formation.
; If using skinny_dip, this change will happen before.
; AFC.cfg line 121
global Machine_tip_toolchange_temp = 0 ; AFC_tip_toolchange_temp

; This step is split into two different movements. First, a fast move to separate the filament
; from the hot zone. Next, a slower movement over the remaining distance of the cooling tube.
; AFC.cfg line 125 and 126
global Machine_tip_unloading_speed = {40,15} ; fast speed (mm/s), cooling tube move (mm/s)
; was AFC_tip_unloading_speed

; This stage moves the filament back and forth in the cooling tube section of the hotend.
; It helps keep the tip shape uniform with the filament path to prevent clogs.
; AFC.cfg line 130 to 134
; Start of the cooling tube in mm.
; Length of the move in mm.
; Initial movement speed to start solidifying the tip in mm/s.
; Fast movement speed in mm/s.
; Number of back and forth moves in the cooling tube.
global Machine_tip_cooling = {35,10,10,50,4} ; was AFC_tip_cooling 

; This is a final move to burn off any hairs possibly on the end of stringy materials like PLA.
; If you use this, it should be the last thing you tune after achieving a solid tip shape.
; AFC.cfg line 138
global Machine_tip_use_skinnydip = false ; Enable skinny dip moves (for burning off filament hairs).
; was AFC_tip_use_skinnydip
; Distance to reinsert the filament, starting at the end of the cooling tube in mm.
; Insertion speed for burning off filament hairs in mm/s.
; Extraction speed (set to around 2x the insertion speed) in mm/s.
; Pause time in the melt zone in seconds.
; Pause time in the cooling zone after the dip in seconds.
; AFC.cfg line 139 to 143
global Machine_tip_skinnydip = {30,30,70,0,0} ; was AFC_tip_skinnydip

;░█▀▄░█▀█░░░█▀█░█▀█░▀█▀░░░█▀▀░█▀▄░▀█▀░▀█▀░░░█▀█░█▀█░█▀▀░▀█▀░░░█░█░█▀▀░█▀▄░█▀▀░█░█░█
;░█░█░█░█░░░█░█░█░█░░█░░░░█▀▀░█░█░░█░░░█░░░░█▀▀░█▀█░▀▀█░░█░░░░█▀█░█▀▀░█▀▄░█▀▀░▀░▀░▀
;░▀▀░░▀▀▀░░░▀░▀░▀▀▀░░▀░░░░▀▀▀░▀▀░░▀▀▀░░▀░░░░▀░░░▀░▀░▀▀▀░░▀░░░░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░▀░▀

; These are the machine features
; 0 = brushing
; 1 = cutting 
; 2 = kicking
; 3 = parking
; 4 = pooping
; 5 = purging
; 6 = start check
; 7 = spoolman support
; 8 = initial unload
global Machine_features={var.brush,var.cut,var.kick,var.park,var.poop,var.purge,var.start,var.spoolman,var.initial_unload} ;

; ########## Additional Info ##########

global Machine_step_through_macro = false ; was AFC_step_through_macro

global Machine_startup_check = false ; was AFC_startup_check

global Machine_last_tool = -1 ; was AFC_last_tool

global Machine_axis_number = vector(3, 0)
; 0 = OM Axis number for X
; 1 = OM Axis number for Y
; 2 = OM Axis number for Z
while iterations < #move.axes
    if move.axes[iterations].letter == "X"
        set global.Machine_axis_number[0] = iterations
    elif move.axes[iterations].letter == "Y"
        set global.Machine_axis_number[1] = iterations
    elif move.axes[iterations].letter == "Z"
        set global.Machine_axis_number[2] = iterations

; ########## Extruder Info ##########

;global Machine_extruder = vector(#global.AFC_unit_CAN_ids, 0)
;while iterations < #global.AFC_unit_CAN_ids
;    var e_driver = move.extruders[tools[global.tool_and_motion[iterations][0]].extruders[0]].driver
;    var e_ms = move.extruders[tools[global.tool_and_motion[iterations][0]].extruders[0]].microstepping.value
;    var e_spm = move.extruders[tools[global.tool_and_motion[iterations][0]].extruders[0]].stepsPerMm
;    var e_j = move.extruders[tools[global.tool_and_motion[iterations][0]].extruders[0]].jerk
;    var e_s = move.extruders[tools[global.tool_and_motion[iterations][0]].extruders[0]].speed
;    var e_a = move.extruders[tools[global.tool_and_motion[iterations][0]].extruders[0]].acceleration
;    var e_c = move.extruders[tools[global.tool_and_motion[iterations][0]].extruders[0]].current

;    ; This is the information about the extruder currently installed in your machine
;    set global.Machine_extruder[iterations] = {var.e_driver,var.e_ms,var.e_spm,var.e_j,var.e_s,var.e_a,var.e_c}    ; This is information about your current extruder. Driver number, microstepping, steps per mm, jerk, max speed, acceleration, current
;    ; was main_extruder

; ########## Start Print ###########

global Gcode_bed_temp = 0                   ; This is used to store the bed temperature from the gcode
; was slicerBedTemp
global Gcode_bed_temp_override = 0           ; This value should be set to something different to override the value from the gcode
; was slicerBedTempOverride
global Gcode_hotend_temp = 0                ; This is used to store the hotend temperature from the gcode
; was slicerHotendTemp
global Gcode_hotend_temp_override = 0        ; This value should be set to something different to override the value from the gcode
; was slicerHotendTempOverride
global Machine_soak_time_override = false            ; This allows the soak time to be overridden
; was soakTimeOverride
global Machine_override_bed_off = false              ; This allows turning off of the bed to be overridden
; was overrideBedOff
global Machine_override_hotend_off = false           ; This allows turning off of the hotend to be overridden
; was overrideHotendOff
global Machine_cancelled = false                   ; This allows the start_print to be cancelled part way through
; was Cancelled
global Machine_tpre_failed = false